version: '3.8'

networks:
  default:
    name: ${NETWORK_NAME:-tv-dashboard-network}

services:
  tv-dashboard:
    build: .
    image: ${IMAGE_NAME:-tv-dashboard}
    container_name: ${CONTAINER_NAME:-tv-dashboard}
    ports:
      - "${PORT:-8080}:80"
    environment:
      # App Config
      - APP_NAME=${APP_NAME:-TV Dashboard}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      
      # Nginx Config
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - NGINX_CLIENT_MAX_BODY_SIZE=${NGINX_CLIENT_MAX_BODY_SIZE:-100M}
      - NGINX_KEEPALIVE_TIMEOUT=${NGINX_KEEPALIVE_TIMEOUT:-65}
      - NGINX_CLIENT_TIMEOUT=${NGINX_CLIENT_TIMEOUT:-60}
      - NGINX_GZIP_ENABLED=${NGINX_GZIP_ENABLED:-true}
      
      # Cache
      - STATIC_ASSETS_CACHE=${STATIC_ASSETS_CACHE:-1y}
      - HTML_CACHE_CONTROL=${HTML_CACHE_CONTROL:-no-cache, no-store, must-revalidate}
      
      # Security
      - SECURITY_HEADERS_ENABLED=${SECURITY_HEADERS_ENABLED:-true}
      - X_FRAME_OPTIONS=${X_FRAME_OPTIONS:-DENY}
      - X_CONTENT_TYPE_OPTIONS=${X_CONTENT_TYPE_OPTIONS:-nosniff}
      - X_XSS_PROTECTION=${X_XSS_PROTECTION:-1; mode=block}
      - SERVER_TOKENS=${SERVER_TOKENS:-off}
      
      # CORS
      - CORS_ENABLED=${CORS_ENABLED:-true}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - CORS_ALLOWED_METHODS=${CORS_ALLOWED_METHODS:-GET,HEAD,OPTIONS}
      - CORS_ALLOWED_HEADERS=${CORS_ALLOWED_HEADERS:-Origin,X-Requested-With,Content-Type,Accept}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-combined}
      - LOG_ACCESS_ENABLED=${LOG_ACCESS_ENABLED:-true}
      - LOG_ERROR_ENABLED=${LOG_ERROR_ENABLED:-true}
      
    volumes:
      - ./logs:/var/log/nginx:rw
    restart: unless-stopped
    
    labels:
      # Traefik
      - "traefik.enable=${TRAEFIK_ENABLE:-true}"
      - "traefik.http.routers.tv-dashboard.rule=Host(`${TRAEFIK_DOMAIN:-tv-dashboard.local}`)"
      - "traefik.http.services.tv-dashboard.loadbalancer.server.port=${TRAEFIK_SERVICE_PORT:-80}" 